Chart update
Groupe-Citypassenger-Inc/Traffic pull request #1
Opened 2021-05-07 15:22 UTC by TimotheCity

- new chart.js version [2.9.4 -> 3.2.1]
- possibility to stack the lines
- some colors were badly initialized with only 5 digits (#xx.xx.x)
- the units displayed on the Y-axis adapt to the value [1o, 1000o -> 1Ko ...].
- the received data are completed to avoid wrong graph
- smaller step to get more data

2021-05-10 12:13 UTC, dohnuts requested changes
Meh, pas mal de truc a modifier et de risque de regression ( et des trucs deja revue ailleur pareil )

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +        pointRadius: 0,
This should be commented to explain what it is

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +        for(let j = 1; j < missingSteps; j++){
Possible de reecrire plus simple sans splice

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.html
> +            </button>
indetation

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +      stacked = metricData[metric]['y']['stacked'] === '' ? undefined : metricData[metric]['y']['stacked'];
Tu as pula fonction is Null Or undef etc... ? plutot que === ?

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +    });
pas de CSS dans le JS merci, typiquement un truc a mettredans le CSS avec un jolie path 

#graph>div>.node

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +          textContainer.style.textDecoration = item.hidden ? 'line-through' : '';
pas de style horsa des ages de style , merci

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +    unitInformation.set('octet', ['o', 'Ko', 'Mo', 'Go', 'To']);
ajoute Po aussi , o est dans un 64bit world

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.ts
> -              suggestedMin: min,    // minimum will be 0, unless there is a lower value.
regressoin ici probablement, le fichie rde conf permet de choisir le ZERO , ce qui permet de zommer sur la variation plutot que ce prendre des graphs plein de vide

2021-05-10 12:13 UTC, dohnuts commented on src/app/graph/graph.component.ts
> -              suggestedMin: min,    // minimum will be 0, unless there is a lower value.
Genre pour une courbe de temperatur voir entre 0 et 10 dans un pc, je pense pas qu on fasse du LOX

2021-05-10 12:13 UTC, dohnuts commented on src/assets/json/config.metrics.json
> +            "en" : "octet",
octet c est pas de l anglais , on dit byte ( pas bit )
Traduit pas sans etre sur ou demande

2021-05-14 14:31 UTC, closed without merging

2021-05-14 14:31 UTC, TimotheCity commented
Outdated PR