Dev
Groupe-Citypassenger-Inc/Traffic pull request #8
Opened 2021-07-08 13:20 UTC by TimotheCity

2021-07-08 13:40 UTC, dohnuts requested changes

2021-07-08 13:40 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +    value *= 1; // turn string to int
https://www.w3schools.com/jsref/jsref_parseint.asp

2021-07-08 13:40 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +    }
autre façon : strlen(value) / 3 ( la divisionentiere de la longeur ) donne le resultat direct de thousand_counter

2021-07-08 13:40 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +      return 'Protocole: ' + context.dataset.protocole;
sur ?

2021-07-08 13:40 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +      let footer = 'Volume: ';
cela va pas etre traduit , probablement un mauvais design ( pas d usage du template html avec des states )

2021-07-08 13:40 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +      data: data,
a sortir dans un un fichier de config ?

2021-07-08 13:40 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +      data: data,
( qui s apelle pas config mais ce que c est ? )

2021-07-15 15:05 UTC, dohnuts requested changes

2021-07-15 15:05 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +  }
a virer useless one line in one liner to hide a oneliner

2021-07-15 15:05 UTC, dohnuts commented on src/app/graph/graph.component.ts
> +  }
moment sais faire , arrete de reinventer la roue :'(

2022-02-22 17:28 UTC, nathangobinet reviewed
Bon...
L'ensemble du code est vraiment pas très bon.
Beaucoup d'imbrications, tout dans le même fichier, aucun respects des standards, des fonctions illisibles.
J'ai arrêter de trop lire à la fin car je me répétait.

Il me semble que tu n'es pas l'auteur original et que tu as fait juste rajouté des bouts ? Right ?
Je pense également qu'avec le travail fait récemment (et ton gros cerveau) tu es en mesures de comprendre les problèmes de ce code et d'y remédier.

Après je constate bien que ce n'est pas le but de cette PR, qui est juste dans un premier temps de régler l'indentation. Donc si tu veux j'approve.

Si le projet est encore d'actualité et qu'il est amené à évoluer dans le futur, il peut être intéressant de passer un petit peu de temps à nettoyer le code... qui en a bien besoin.

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>  export interface unit_conversion {
snake_case not good
js recomendations are camelCase and PascalCase

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>  export interface unit_conversion {
Mais bon, ca sert a riend e changer tout le code donc laisse comme ca

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +  _unit: unit_conversion = {
Constante

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>    default_date: Date = new Date();
contante

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>    default_value: number = 1;
constante ?

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    private _formBuilder: FormBuilder,
why _ ?

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
créer une fonction isMobile et fait
```
this.is_mobile = this.isMobile();
```

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      }
A mettre dans une fonction avec un nom explciatif

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      }
A mettre dans une fonction avec un nom explciatif

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    if (this.form_group_controls_subscription != undefined) {
!==

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>          console.log(query)
?

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>          let date = new Date(this.params_list['date'][index])
const

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +          if (isDevMode()) {
Ne doit pas rester dans le code

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +  add_records(query: string): void {
Le code de la fonction est catastrophique
Tu peux pas créer une constante record par défaut et juste modifié les élements qui dépendent de query ?

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      let user_config_url = user_config_base_url + this.user_information.username + ".json.nousNeVoulousPlusDeConfigPerso";
const

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    this.base_url_buffer = '/' + this.password + '/prombuffer/' + this.group_name + '/api/v1';
string interpolation

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +  default_end_time: any = 0;
consatnte ?

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      let user_config_url = user_config_base_url + this.user_information.username + ".json.nousNeVoulousPlusDeConfigPerso";
string interpolation

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>          console.log('Handling error locally and rethrowing it...', err);
console.error

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    if (isDevMode()) {
a enlever

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    if (isDevMode()) {
a enlever

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      let range = scrape_interval * 4; //safe
const

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      let query: string = metric_name;
const

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      let query: string = metric_name;
PAs besoin de typé implicitement

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    if (isDevMode()) console.log(this.metrics_config);
a enlever

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      }
inverse if pour meilleur lisibilité

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    let end_time: number;
homgéninise const let

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      if (isDevMode()) console.log(this.graphs_records[metric]);
a enlnver

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
const let

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>      if (isDevMode()) console.log(end_time + ' ' + start_time);
a enlever

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +          let box_filter: string = 'job=~"' + selected_box + '.*"';
Rien compris

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +        if (isDevMode()) console.log(response);
:-/

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>        }
iverse if pour alléger

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
const let

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
Toute la fonction et cauchemardesque, je pense que tu t'y prend mal

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
> +    if (isDevMode()) console.log(data_to_parse);
:-/

2022-02-22 17:28 UTC, nathangobinet commented on src/app/graph/graph.component.ts
>          );
:satan:

2022-02-23 08:49 UTC, TimotheCity commented on src/app/graph/graph.component.html
>        <div *ngIf='graphs_records.hasOwnProperty(query)'>
Si malheureusement, et ça entraine des merdes visuellement dans la coloration du code, je vais tout clean après avoir ajouter un linter

2022-05-19 09:38 UTC, closed without merging